"""Permitir NULL en usuario_id y comentario

Revision ID: 43c3270a5483
Revises: 8fc4e7aad4b2
Create Date: 2025-06-08 22:55:39.435354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c3270a5483'
down_revision = '8fc4e7aad4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_estados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentario', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('observacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_estados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comentario')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
