"""Migración inicial

Revision ID: 59b5e4485127
Revises: 
Create Date: 2025-06-03 22:40:00.985563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b5e4485127'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', 'NO_ESPECIFICA', name='genero'), nullable=False),
    sa.Column('pais', sa.Enum('ARGENTINA', 'BOLIVIA', 'CHILE', 'COLOMBIA', 'ECUADOR', 'MEXICO', 'PERU', 'URUGUAY', 'VENEZUELA', 'GUATEMALA', 'HONDURAS', 'EL_SALVADOR', 'NICARAGUA', 'COSTA_RICA', 'PANAMA', 'CUBA', 'REPUBLICA_DOMINICANA', 'PARAGUAY', 'PUERTO_RICO', name='pais'), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('telefonos', sa.String(length=100), nullable=True),
    sa.Column('emails', sa.String(length=150), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=100), nullable=False),
    sa.Column('institucion', sa.String(length=150), nullable=False),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.Column('experiencia_tech', sa.Text(), nullable=True),
    sa.Column('situacion_laboral', sa.String(length=100), nullable=True),
    sa.Column('ingresos', sa.Float(), nullable=True),
    sa.Column('acceso_tecnologia', sa.String(length=255), nullable=True),
    sa.Column('dependientes', sa.Integer(), nullable=True),
    sa.Column('programa_solicitado', sa.Enum('PROGRAMADOR_JUNIOR', 'CIBERSEGURIDAD', name='programa'), nullable=False),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'VIRTUAL', 'HIBRIDA', name='modalidad'), nullable=False),
    sa.Column('disponibilidad', sa.String(length=255), nullable=True),
    sa.Column('motivacion', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('EN_REVISION', 'APROBADO', 'RECHAZADO', 'INCOMPLETO', 'CANCELADO', name='estadosolicitud'), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False),
    sa.Column('operacion', sa.String(length=20), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('datos_antes', sa.Text(), nullable=True),
    sa.Column('datos_despues', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('becados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('cohorte', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'VIRTUAL', 'HIBRIDA', name='modalidad'), nullable=False),
    sa.Column('sede', sa.String(length=100), nullable=True),
    sa.Column('plataforma_externa_id', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'EN_PAUSA', 'DESERTOR', 'GRADUADO', 'SUSPENDIDO', name='estadobeca'), nullable=True),
    sa.Column('fecha_ultimo_cambio_estado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['solicitantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitante_id')
    )
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('EN_REVISION', 'APROBADO', 'RECHAZADO', 'INCOMPLETO', 'CANCELADO', name='estadosolicitud'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['solicitantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_becado_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('becado_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'EN_PAUSA', 'DESERTOR', 'GRADUADO', 'SUSPENDIDO', name='estadobeca'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['becado_id'], ['becados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_becado_historial')
    op.drop_table('historial_estados')
    op.drop_table('becados')
    op.drop_table('auditoria_login')
    op.drop_table('auditoria_actividad')
    op.drop_table('usuarios')
    op.drop_table('solicitantes')
    # ### end Alembic commands ###
